---
name: "Kodi Sync Queue Custom"
guid: "36efe90f-3a68-4ef4-b400-af54fec2ad02"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-kodisyncqueue.png"
version: 14
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Sync all media changes with Kodi clients"
description: "This plugin will track all media changes while Kodi clients are offline to decrease sync times."
category: "General"
artifacts:
  - "Jellyfin.Plugin.KodiSyncQueue.dll"
  - "LiteDB.dll"
changelog: |2-
  ### Bug Fixes ###
  - Implement a database upgrade system, properly migrate ItemId to Guid (#107) @Insprill
