name: Build and Release Jellyfin Plugin

on:
  push:
    tags:
      - 'v*'  # Triggers only on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'  # Or '7.0.x' depending on your target framework

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Plugin
        run: |
          dotnet publish Jellyfin.Plugin.KodiSyncQueue.csproj -c Release -o publish

      - name: Package Plugin
        run: |
          cd publish
          zip -r Jellyfin.Plugin.KodiSyncQueue.zip *

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: publish/Jellyfin.Plugin.KodiSyncQueue.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
